sudo: required
services:
  - docker

before_install:
  - docker build -t kartheekgopal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kartheekgopal/docker-react npm run test -- --watchAll=false